import Head from 'next/head';
import styles from '@/styles/home.module.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import AboutMe from '@/components/page_content/about_me';


export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
			</Head>
			<main className={styles.container}>
				<Header />
				<AboutMe />
				<Footer />
			</main>
		</>
	);
}
