import Head from 'next/head';
import styles from '../styles/home.module.css';
import Projects from '../components/projects';
import NavMenu from '../components/nav_menu';
import Header from '../components/header';
import Footer from '../components/footer';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
			</Head>
			<main className={styles.container}>
				<Header />
				<NavMenu />
				<Projects />
				<Footer />
			</main>
		</>
	);
}
